### PR TITLE
Added column support  for PostgreSQL

### PR DESCRIPTION
**Pull request by pooja1pathak**
Added column support for PostgreSQL, logging and exception handling.
I have followed the file structure of HDFS and created aggregator, backend for PostgreSQL.
Added log4j.properties for logging.

### CODE REVIEW

**Comment by anmunoz** [comment]
Hi @pooja1pathak,

Thanks a lot for your contribution, I have been checking the code and some thinks need to be considered. First, the logging classes and driver included are not needed, we use the native nifi. This is because in the future we want to integrate these processors to Apache nifi project and these files add unnecessary code. Also the error classes are redundant, for example: Draco bad configuration is never used due to the fact that the properties are limited to defined values and also that nifi has classes for validation.
I suggest you wait for the developer guidelines for adding new features and code to existing or new processors.

Best Regards,
Andrés

**Comment by pooja1pathak** [comment]
Hi @anmunoz ,
Thanks for your helpful comment.
I need column support in postgreSQL for my project.
Will it be ok if I remove logging and Error handling? 
Please guide me further.

**Comment by pooja1pathak** [comment]
Hi @anmunoz ,
I have a query regarding stable branch. I want to use draco's stable branch in my application.
Which branch should I choose: master or any other stable branch is available?

**Comment by anmunoz** [comment]
Hi @pooja1pathak ,
I have been checking your pull request and it isn't follow the structure of the classes or methods of Draco's, please find in the branch <column_support> of this repo the correct way to add this feature, if you want, you can add this code to your fork and then make a new pull request for adding this to fiware-draco repo. Thank for you collaboration.

Best Regards,

**Pull request closed without merging**
